config/routes.rb
Kaaywin::Application.routes.draw do
  
  get "tickets/index"
  get "tickets/show"
  get "tickets/print"
  get "tickets/cancel"
  get "tickets/destroy"
  get "grid_test/test"
  get "betting/index"
  get "bets/destroy"
  get "sports/new"
  get "sports/edit"
  get "sports/create"
  get "sports/update"
  get "sports/destroy"
  get "events/new"
  get "events/index"
  get "events/edit"
  get "events/update"
  get "events/destroy"
  get "leagues/new"
  get "leagues/create"
  get "leagues/distroy"
  get "leagues/index"
  get "main/index"
  get "events/display/:id", to: 'events#show', as: 'display_event'
    get "tickets/display/:id", to: 'tickets#show', as: 'display_ticket'
  get "events/results" , to:'events#results', as: 'results'
   get "leagues/events/:id" , to:'events#index', as: 'league_events'
  get "/leagues/:id", to: 'leagues#index', as: 'sport_leagues'
  get "leagues/", to: 'leagues#index', as: 'back_to_sport_leagues'
  get "/events/enter_empty_results", to: "events#enter_empty_results", as: "empty_results"
  get "/users/add_credit/:id", to: "users#add_credit", as: "add_credit"

  post "/users/update_balance", to: "users#update_balance", as: "update_balance"
 post "events/search"
 post "events/search_by_id"
  post "events/addbet"

 get "/scratch_cards/generate_cards", to: 'scratch_cards#generate_cards', as: 'generate_cards'

 post "/scratch_cards/verify_card", to: 'scratch_cards#verify_card', as: 'verify_card'
 post "/scratch_cards/unverify_card", to: 'scratch_cards#unverify_card', as: 'unverify_card'
 get "/scratch_cards/print_card/:id", to: 'scratch_cards#print_card', as: 'print_card'
 post "/scratch_cards/generate", to: 'scratch_cards#generate', as: 'generate'
   get "/betting/:id", to: 'betting#placebet', as: 'placebet'
   post '/betting/reset_bet_slip', to: 'betting#reset_bet_slip', as:'reset_bet_slip'
    post '/betting/update_stake', to: 'betting#update_stake', as:'update_stake'
    post '/betting/issue_ticket', to: 'betting#issue_ticket', as: 'issue_ticket'

    post '/betting/front_signin', to: 'betting#front_signin', as: 'front_signin'
     post '/betting/front_signout', to: 'betting#front_signout', as: 'front_signout'

   post "/betting/remote_bet/:id", to: 'betting#remove_bet', as: 'remove_bet'

  get "events/:id", to: 'events#enter_result', as: 'result'
  post "events/placebet"
  post "events/new"
  patch "events/save_result/:id", to:'events#save_result', as: 'save_result'
    post "events/save_results", to:'events#save_results', as: 'save_results'
 

  resources :users
  resource :results
  resources :leagues
  resources :bet_types
  resources :transactions

  resources :events do
    member do
      put 'save_result'
    end
  end

  resources :tickets
  resources :sports
  resources :bets
  resources :sessions, only: [:new, :create, :destroy]
  resources :scratch_cards

  get "users/new"
  root 'admin#home'
  match '/contact', to: 'admin#contact', via: 'get'
  match '/about', to: 'admin#about', via: 'get'
  match '/register', to: 'users#new', via: 'get'

  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/controllers/betting_controller.rb
class BettingController < ApplicationController
  
	# # Author: Hussein Diab-Ghanem
	# Date: 9th April 2014
	# this controller will be responsible for all bet placing, ticket generation and ticket printing

  def index
  	@leagues= League.all
  	session[:betSlip] = nil
  	@emptySlip = true
  	@front_office = true
  end

  def test_image
  end


  # actual bet placing that updates the betting slip session instance
  def placebet
  	@front_office = true
  	session[:betSlip] = BetSlip.new unless !session[:betSlip].nil?

    if session[:current_card] # if a scratch-card is verified update the betSLip
      session[:betSlip].stake = session[:current_card].credit
    end
  	@emptySlip = false
  

  	betItem = BetItem.find(params[:id])
  	# get the event as we will need its name to avoid mulitple bets placed on the same
  	#event
  	event = betItem.bet.event

  	#add the bet to the slip together will all dta needed for rendering
  	# i.e the event name, pick, odds, etc
  	# we will also need to store the bet item to clone it later on 
  	session[:betSlip].addPick(betItem.id, betItem.name,betItem.odds,betItem.bet.bet_type.name, event.name)
  
  	#puts(session[:betSlip].picks)
  	puts(session[:betSlip].eventNames)
  	#puts(event.name)
 	
  	respond_to do |format|
  		format.html
  		format.js
  		end
  	end

  	def remove_bet

  		# get the bet array index so we can remove it	
  		session[:betSlip].removeBet(params[:id].to_i)
  		respond_to do |format|
  			format.html
  			format.js
  		end
  	end

  	# the user updated the stae amount
  	def update_stake
  		session[:betSlip].stake = params[:amount].to_f

  		respond_to do |format|
  			format.html
  			format.js
  		end
  	end

  	def reset_bet_slip # used to clear all bets
  		session[:betSlip].reset
  		respond_to do |format|
  			format.html
  			format.js
  		end
  	end

  	def issue_ticket # issue the ticket

      # lets update the transactions table with what this user just spent
      # but we need to decide if this was a scratch card transaction or
      # regular one

      if !session[:current_card]  # this is a regular logged in user
        if current_user.balance >= session[:betSlip].stake
          Transaction.create(amount: session[:betSlip].stake.to_f*-1, user_id: current_user.id, transaction_type: 1, comment: 'web entry')
  		   # return the ticket for printing
         @ticket = session[:betSlip].createTicket_for_user(current_user.id)
  
        else 
          flash.now[:warning] = "insufficient balance"
          
        end
      else  # this has to be a scratch card
         # return the ticket for printing
          @ticket = session[:betSlip].createTicket_for_card(session[:current_card].id)
          session[:current_card].status = 2  # set the card to used
          session[:current_card].save  
          sign_out_card  # sign the card out as its been used
      end
        session[:betSlip].reset
  		respond_to do |format|
  			format.html
  			format.js
  		end

  	end

 # this method is invoked only when the user signs in from the front end
    def front_signin
          user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
          sign_in user
      
        else
         flash.now[:error] = 'Invalid email/ password combination'
      
        end
        redirect_to action: 'index'
    end

    # this method is invoked only when the user signs out from the front end
    def front_signout 
      sign_out
      redirect_to action: 'index'
    end
  end

app/helpers/betting_helper.rb
module BettingHelper
end

app/views/betting/_betslip.html.erb
<div id = 'replaceable'>
<body style="background-attachment: fixed; background-repeat: no-repeat;" background="/assets/bground.jpg">

<%if signed_in? %>
Balance: <%=current_user.balance %>
<div class="alert alert-error"><%=flash[:warning]%></div>
<%end%>
<% if session[:betSlip].picks_id.length == 0 %>


Your betting slip is empty.  Please click on bets to add.

<%else%>



<% (0..(session[:betSlip].picks_id.length-1)).each do |cursor| %>

<h2><%=session[:betSlip].eventNames[cursor]%><%=session[:betSlip].betNames[cursor]%></h2>


<div class = "left"><slipGreen><%=session[:betSlip].picks_name[cursor]%></slipGreen></div>
<div class = "right"><slipNumber><%=session[:betSlip].picks_odds[cursor].to_s+"  "%></slipNumber><%=link_to content_tag(:span,'', class: "glyphicon glyphicon-remove")+ "", remove_bet_path(cursor), method: :post, :remote => true, class: "glyphicon gyphicon-star remove_fields"%></div>

<br>

 <slipDivider>--------------------------------------</slipDivider>
<%end%>

<ul style ="list-style: none;">


<li> 
<slipGreen>Total bets:</slipGreen>
<div class="right"><slipNumber><%=session[:betSlip].picks_id.length %></slipNumber></div>
</li>

<li>
<slipGreen>Total odds:</slipGreen>
<div class="right"><slipNumber><%=session[:betSlip].totalOdds %></slipNumber></div>
</li>

<li><slipGreen>Stake:</slipGreen>

<%if !session[:current_card] %>
<div class = "right"><slipNumber><%=text_field :stake,:amount, :value  => session[:betSlip].stake.to_s, :size =>10, :maxlength =>"4", :onchange => "$.ajax({
	type: 'POST',
	url: 'update_stake',
	data: {amount: $('#stake_amount').val()
		},
	dataType: 'script'
	//do nothing
	

	});"%></slipNumber></div>
	</li>
<%end%>

<% if session[:current_card] %>
<div class = "right"><slipNumber><%=text_field :stake,:amount, :value  => session[:betSlip].stake.to_s, :size =>10, :maxlength =>"4", :disabled => true %>
</slipNumber>
</div>
<%end%>


	
<li>
<slipGreenBold>Possible winnings:</slipGreenBold>
<div class = "right"><slipNumber><%=session[:betSlip].winnings.to_s+ "  GMD" %></slipNumber></div>
</li>
</ul>
<br>
<%if session[:betSlip].picks_id.length >=3 && (signed_in? || session[:current_card]) %>
<center><%=link_to "place bet",issue_ticket_path, :class =>"btn btn-danager", method: :post, :remote => true%>
</center>
<%end%>
<center><%=link_to "Remove all", reset_bet_slip_path, method: :post,:remote => true%></center>

<%end%> 




</div>

app/views/betting/_login_status.html.erb
<div id = "replaceableLoginStatus">
<%if !signed_in? %>
<div class="span6 offset11 navbar navbar-fixed-top">
  
     

    
    
      
        
         <%= form_for(:session, url: sessions_path) do |f| %>
        <table border="0">
        <tr>
        
      <td><%=f.text_field :email, :placeholder =>"username" %></td>  <td><%=f.password_field :password, :placeholder => "password" %></td>
     
      <td>
      <center>
      <%=f.submit "Sign in" %>
      </center>
      </td>
      </tr>
      </table>

    <% end %>
</div>
<%end%>

<%if signed_in? %>
<div class="span6 offset11 navbar navbar-fixed-top">
  
     

    
    
      
        
         
        <table id = "miniTable">
        <tr>
        
      <td><%=current_user.name%></td>  <td><%=current_user.balance.to_s + ' GMD'%></td>
     
      <td>
      <center>
      <%=link_to  "Sign out", front_signout_path, method: :post  %>
      </center>
      </td>
      </tr>
      </table>

</div>
<%end%>

</div>

app/views/betting/index.html.erb
<div id = "replaceableLoginStatus">

 <div class="navbar navbar-fixed-top navbar-inverse" role="navigation" id = 'frontOfficeBar'>

<ul class="nav pull-right">

<%if !signed_in? %>




     

    
    
      
        
        
        <table border="0", cellpadding="0px">
        <tr>
         <%= form_for(:session, url: front_signin_path) do |f| %>
        
      <td><%=f.text_field :email, :placeholder =>"username" %></td>  <td><%=f.password_field :password, :placeholder => "password" %></td>
     
      <td>
      <center>

      <%=f.submit "Sign in"%>
       <% end %>
      </center>
      </td>
      </tr>
      <%if !session[:current_card] %>
      <tr>
     
         
      <%=form_tag(controller: "scratch_cards", action: "verify_card", method: "get") do %>
       <td><%=label_tag(:label, "Verify a Scratch card") %></td>
       <td><%=password_field_tag(:hidden_number,'', :placeholder => 'code') %></td>
       <td><%=submit_tag("Verify",class: "btn btn-small btn-primary")%></td>
       <%end%>
       </td>
       </tr>
       <%end%>
      </table>

  

<%end%>


<%if session[:current_card] %>


    
        <table id = "miniTable">
        <tr>
        
      <td>Scratch Card Activated</td>  <td><%=session[:current_card].credit.to_s+ ' GMD'%></td>
     
      <td>
      <center>
      <%=link_to  "Cancel", unverify_card_path, method: :post %>
      </center>
      </td>
      </tr>
      </table>

<%end%>
<%if signed_in? %>

  
     

    
    
      
        
         
        <table id = "miniTable">
        <tr>
        
      <td><%=current_user.name%></td>  <td><%=current_user.balance.to_s + ' GMD'%></td>
     
      <td>
      <center>
      <%=link_to  "Sign out", front_signout_path, method: :post %>
      </center>
      </td>
      </tr>
      </table>


<%end%>

</ul>
</div>
</div>

<br>
<br>


<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2 offset1">
    <div class = "well">
           
            
           
<table class = "table table-hover table-striped table-bordered" id = 'fheader'><thead><tr><th>SPORT'S MENU</th></tr></thead></table>
             
      <div class = "collapse navbar-collapse navHeaderCollapse">
            <ul class = "nav navbar-nav navbar-left">

                <a href = "#" class = "dropdown-toggle" data-toggle ="dropdown">Football</a>
                <ul class = "dropdown-menu">
                   <li><a href = "#">All Today's events</a></li>
                   <li><a href = "#">All Tomorrows's events</a></li>
                    <%League.all.each do |league| %>
                    <li><a href="#"><%=league.name%></a></li>
                
                  <%end%>  
                </ul>

           
              </ul>
              </div>
              </div>

            
   



      <br>
      <br>

     <div class="well">   

     <table class = "table table-hover table-striped table-bordered" id = 'fheader'><thead><tr><th>SEARCH</th></tr></thead></table>
             
            <%=form_tag(controller: "events", action: "search", method: "get" ) do %>
          

                 <%= label_tag(:q, "") %>
                  <%= text_field_tag(:q,'', :placeholder => 'Event id')%>
                    <%= text_field_tag(:q,'', :placeholder => 'Event name')%>
                  <%=submit_tag("search",class: "btn btn-small btn-primary")%>
                  <%end%>
         
      </div><!--/.well -->
    </div><!--/span-->

    
    <div id = "replaceableFixtures">

    <div class="span5 span-fixed-sidebar" id="fixtures">
          
             <%@leagues.each do |league|%>
      <table class = "table table-hover table-striped table-bordered" id = 'fheader'><thead><tr><th><%=league.name%></th></tr></thead></table>
    
       <%league.events.each do |event|%>
        
        
          <fleague><%=event.date.strftime("%A") + " " +event.date.to_date.to_s%></fleague>
          <br>
        <eventTitle><%=event.name%></eventTitle>
          <br>
        
         
         <%event.bets.each do |bet| %>
        

          

            <%if bet.bet_type.name.downcase.include? "versus" and bet.bet_type.name.downcase.include? "draw"%>
              <div class = "left"><betTitle><%=event.name%></betTitle></div>
          
           
            <div class = "left"><betTitle><%=bet.bet_type.name%></betTitle></div>
            <div class = "right">
           <%bet.bet_items.each do |bet_item| %>
            <%=link_to bet_item.odds.to_s ,placebet_path(bet_item.id), :class =>"btn btn-danager btn-mini", method: :get, :remote => true%>
           <%end%>
           </div>
           <br>

           <%else%>
         
         
          <div class = "left"><betTitle><%=event.name+" "+bet.bet_type.name%></betTitle></div>
         <br>

          
           <%bet.bet_items.each do |bet_item| %>
        
           <ul style ="list-style: none;">
           <li>
   <betFont><%=bet_item.name%></betFont>

             <div class = "right"><table border = "0"><tr><td><%=link_to bet_item.odds.to_s,placebet_path(bet_item.id), :class =>"btn btn-danager btn-mini",method: :get, :remote => true%></td></tr></table></div>
           
             </li>
             </ul>
          
           <%end%>
              
          

          <br>
          <%end%>
         <%end%>
         
         <%end%>
       <%end%>
       
      </div> <!--- fixtures -->
    </div>

  
      
      <div class="span2 offset0">
      
      
        <div id ="well">         
           

          <li class="nav-header"><center><b>Betting Slip</b></center></li>
          <div id = 'replaceable'>Your betting slip is empty.  Please click on bets to add.</div>

         
       

      </div><!--/.well -->
      
      <img src= "/assets/betslip.png", id = "slip2">
     
    
      
    </div><!--/span-->
    
     
      
  </div><!--/row-->

 <div class="alert alert-error"><%=flash[:success]%></div>

</div><!--/.fluid-container-->

app/views/betting/issue_ticket.js.erb
$('#replaceable').html("<%=j render partial: '/betting/betslip'%>");
$('#replaceableLoginStatus').html("<%=j render partial: '/betting/login_status'%>");
$('#replaceableFixtures').html("<%=j render partial: '/tickets/comitted_ticket'%>");

app/views/betting/placebet.js.erb
$('#replaceable').html("<%=j render partial: '/betting/betslip'%>");

app/views/betting/remove_bet.js.erb
$('#replaceable').html("<%=j render partial: '/betting/betslip'%>");

app/views/betting/reset_bet_slip.js.erb
$('#replaceable').html("<%=j render partial: '/betting/betslip'%>");

app/views/betting/test_image.html.erb
 <body style="background-attachment: fixed; background-repeat: no-repeat;" background="/assets/bground.jpg">

 <table border = 0>
 <tr>
 <td>
 <img src= "/assets/betslip1.png", id = "slip2">
 </td>
 </tr>
 <tr>
 <td>
 <img src= "/assets/betslip.png", "slip2">
 </td>
 </tr>
 </table>

app/views/betting/update_stake.js.erb
$('#replaceable').html("<%=j render partial: '/betting/betslip'%>");