config/routes.rb
Kaaywin::Application.routes.draw do
  
  get "tickets/index"
  get "tickets/show"
  get "tickets/print"
  get "tickets/cancel"
  get "tickets/destroy"
  get "grid_test/test"
  get "betting/index"
  get "bets/destroy"
  get "sports/new"
  get "sports/edit"
  get "sports/create"
  get "sports/update"
  get "sports/destroy"
  get "events/new"
  get "events/index"
  get "events/edit"
  get "events/update"
  get "events/destroy"
  get "leagues/new"
  get "leagues/create"
  get "leagues/distroy"
  get "leagues/index"
  get "main/index"
  get "events/display/:id", to: 'events#show', as: 'display_event'
    get "tickets/display/:id", to: 'tickets#show', as: 'display_ticket'
  get "events/results" , to:'events#results', as: 'results'
   get "leagues/events/:id" , to:'events#index', as: 'league_events'
  get "/leagues/:id", to: 'leagues#index', as: 'sport_leagues'
  get "leagues/", to: 'leagues#index', as: 'back_to_sport_leagues'
  get "/events/enter_empty_results", to: "events#enter_empty_results", as: "empty_results"
  get "/users/add_credit/:id", to: "users#add_credit", as: "add_credit"

  post "/users/update_balance", to: "users#update_balance", as: "update_balance"
 post "events/search"
 post "events/search_by_id"
  post "events/addbet"

 get "/scratch_cards/generate_cards", to: 'scratch_cards#generate_cards', as: 'generate_cards'

 post "/scratch_cards/verify_card", to: 'scratch_cards#verify_card', as: 'verify_card'
 post "/scratch_cards/unverify_card", to: 'scratch_cards#unverify_card', as: 'unverify_card'
 get "/scratch_cards/print_card/:id", to: 'scratch_cards#print_card', as: 'print_card'
 post "/scratch_cards/generate", to: 'scratch_cards#generate', as: 'generate'
   get "/betting/:id", to: 'betting#placebet', as: 'placebet'
   post '/betting/reset_bet_slip', to: 'betting#reset_bet_slip', as:'reset_bet_slip'
    post '/betting/update_stake', to: 'betting#update_stake', as:'update_stake'
    post '/betting/issue_ticket', to: 'betting#issue_ticket', as: 'issue_ticket'

    post '/betting/front_signin', to: 'betting#front_signin', as: 'front_signin'
     post '/betting/front_signout', to: 'betting#front_signout', as: 'front_signout'

   post "/betting/remote_bet/:id", to: 'betting#remove_bet', as: 'remove_bet'

  get "events/:id", to: 'events#enter_result', as: 'result'
  post "events/placebet"
  post "events/new"
  patch "events/save_result/:id", to:'events#save_result', as: 'save_result'
    post "events/save_results", to:'events#save_results', as: 'save_results'
 

  resources :users
  resource :results
  resources :leagues
  resources :bet_types
  resources :transactions

  resources :events do
    member do
      put 'save_result'
    end
  end

  resources :tickets
  resources :sports
  resources :bets
  resources :sessions, only: [:new, :create, :destroy]
  resources :scratch_cards

  get "users/new"
  root 'admin#home'
  match '/contact', to: 'admin#contact', via: 'get'
  match '/about', to: 'admin#about', via: 'get'
  match '/register', to: 'users#new', via: 'get'

  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/controllers/bet_types_controller.rb
class BetTypesController < ApplicationController

# Author: Hussein Diab-Ghanem
# Date: 10th April 2014
# 

 before_action :signed_in_user, only: [:index, :edit, :update, :destroy]

  before_action :admin_user, only: [:destroy, :new, :edit]

  def new
    @bet_type = BetType.new # create a blank bettype object 
  end

  def create
    @bet_type = BetType.new(user_params) # save the bet type
   
    if @bet_type.save
      flash[:notice] = "Bet Type successfully registered"
      redirect_to bet_types_url
    else
      render 'new'
    end

  end

  def edit # edit bet type details
    @bet_type = BetType.find(params[:id])
  end

  def update
    @bet_type = BetType.find(params[:id])
   
    if @bet_type.update_attributes(user_params) # get the protected user params
      flash[:success] = "Bet_type updated"
      redirect_to bet_types_url
    else
      render 'edit'
    end
  end


  def destroy
    BetType.find(params[:id]).destroy
    flash[:success] = "Bet Type successfully deleted"
    redirect_to bet_types_url
  end

  def index
    @bet_types = BetType.paginate(page: params[:page])
  end

  private
  def user_params # to prevent mass assginement security vulnerabily
    params.require(:bet_type).permit(:name)
  end
  def admin_user
    redirect_to(root_url) unless current_user.role_id <3
  end


end

app/helpers/bet_types_helper.rb
module BetTypesHelper
end

app/views/bet_types/_bet_type.html.erb
<tr>
<td>

<%=bet_type.name%>

</td>

<% if current_user.role_id %>
<td><%= link_to "delete", bet_type, method: :delete, data: {confirm: "Are you sure?"} %>
<%= link_to "edit", edit_bet_type_path(bet_type)  %></td>
<%end%>

</tr>

app/views/bet_types/_sport.html.erb
<tr>
<td>
<%if fromResultsMenu%><%=link_to bet_type.name, sport_leagues_path(sport.id), :remote =>true%><%else%>

<%=bet_type.name%>
<%end%>
</td>
<td><%=bet_type.created_at%></td>
<% if current_user.role_id < 3 and !fromResultsMenu %>
<td><%= link_to "delete", bet_type, method: :delete, data: {confirm: "Are you sure?"} %>
<%= link_to "edit", edit_bet_type_path(bet_type)  %></td>
<%end%>

</tr>

app/views/bet_types/create.html.erb
<h1>Sports#create</h1>
<p>Find me in app/views/sports/create.html.erb</p>

app/views/bet_types/edit.html.erb
<% provide(:title, 'Edit Bet Type') %>
<div class = "itemForm">
<h1>Please enter Bet Type details: </h1>
<div class = "row">
	<div class = "span3 offset1">
		<%=form_for(@bet_type) do |f| %>
			<%=render 'shared/error_messages_bet_types' %>
			<%= f.label :name %>
			<%= f.text_field :name %>

			
			<br><br>
			<%=f.submit "Save changes", class: "btn btn-large btn-primary" %>
			<%end%>
		</div>
	</div>	
</div>

app/views/bet_types/index.html.erb
<div id = "replaceable">
<div class= "container">
<div class = "row">
<div class = "span10">
<% provide(:title, "All Bet Types") %>
<center> <h1>All Bet Types</h1>
<%if current_user.role_id <3 %><%= button_to "Register a new Bet Type", new_bet_type_path, method: :get %> <%end%>
</center> 

<div class="kaaywintable1">
<%fromResultsMenu=false%>
		<table>
	
		<tr>
		<td>Name</td>
		<td>Actions</td>
		
		</tr>

	<%= render @bet_types%>
	</table>
	

	
	<br>
	
	</div>
	</div>
	</div>
	</div>
</div>	

app/views/bet_types/new.html.erb
<% provide(:title, 'New Bet Type') %>
<h1>Please enter Bet Type details: </h1>
<div class = "row">
	<div class = "span6 offset3">
		<%=form_for(@bet_type) do |f| %>
			<%=render 'shared/error_messages_bet_types' %>
			<%= f.label :name %>
			<%= f.text_field :name %>
			
			
			<%=f.submit "Register this Bet Type", class: "btn btn-large btn-primary" %>
			<%end%>
		</div>
	</div>	

app/views/bet_types/update.html.erb
<h1>Sports#update</h1>
<p>Find me in app/views/sports/update.html.erb</p>