config/routes.rb
Kaaywin::Application.routes.draw do
  
  get "tickets/index"
  get "tickets/show"
  get "tickets/print"
  get "tickets/cancel"
  get "tickets/destroy"
  get "grid_test/test"
  get "betting/index"
  get "bets/destroy"
  get "sports/new"
  get "sports/edit"
  get "sports/create"
  get "sports/update"
  get "sports/destroy"
  get "events/new"
  get "events/index"
  get "events/edit"
  get "events/update"
  get "events/destroy"
  get "leagues/new"
  get "leagues/create"
  get "leagues/distroy"
  get "leagues/index"
  get "main/index"
  get "events/display/:id", to: 'events#show', as: 'display_event'
    get "tickets/display/:id", to: 'tickets#show', as: 'display_ticket'
  get "events/results" , to:'events#results', as: 'results'
   get "leagues/events/:id" , to:'events#index', as: 'league_events'
  get "/leagues/:id", to: 'leagues#index', as: 'sport_leagues'
  get "leagues/", to: 'leagues#index', as: 'back_to_sport_leagues'
  get "/events/enter_empty_results", to: "events#enter_empty_results", as: "empty_results"
  get "/users/add_credit/:id", to: "users#add_credit", as: "add_credit"

  post "/users/update_balance", to: "users#update_balance", as: "update_balance"
 post "events/search"
 post "events/search_by_id"
  post "events/addbet"

 get "/scratch_cards/generate_cards", to: 'scratch_cards#generate_cards', as: 'generate_cards'

 post "/scratch_cards/verify_card", to: 'scratch_cards#verify_card', as: 'verify_card'
 post "/scratch_cards/unverify_card", to: 'scratch_cards#unverify_card', as: 'unverify_card'
 get "/scratch_cards/print_card/:id", to: 'scratch_cards#print_card', as: 'print_card'
 post "/scratch_cards/generate", to: 'scratch_cards#generate', as: 'generate'
   get "/betting/:id", to: 'betting#placebet', as: 'placebet'
   post '/betting/reset_bet_slip', to: 'betting#reset_bet_slip', as:'reset_bet_slip'
    post '/betting/update_stake', to: 'betting#update_stake', as:'update_stake'
    post '/betting/issue_ticket', to: 'betting#issue_ticket', as: 'issue_ticket'

    post '/betting/front_signin', to: 'betting#front_signin', as: 'front_signin'
     post '/betting/front_signout', to: 'betting#front_signout', as: 'front_signout'

   post "/betting/remote_bet/:id", to: 'betting#remove_bet', as: 'remove_bet'

  get "events/:id", to: 'events#enter_result', as: 'result'
  post "events/placebet"
  post "events/new"
  patch "events/save_result/:id", to:'events#save_result', as: 'save_result'
    post "events/save_results", to:'events#save_results', as: 'save_results'
 

  resources :users
  resource :results
  resources :leagues
  resources :bet_types
  resources :transactions

  resources :events do
    member do
      put 'save_result'
    end
  end

  resources :tickets
  resources :sports
  resources :bets
  resources :sessions, only: [:new, :create, :destroy]
  resources :scratch_cards

  get "users/new"
  root 'admin#home'
  match '/contact', to: 'admin#contact', via: 'get'
  match '/about', to: 'admin#about', via: 'get'
  match '/register', to: 'users#new', via: 'get'

  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/event.rb
class Event < ActiveRecord::Base
	validates :name, presence: true
	validates :date, presence: true
	belongs_to :league
	has_many :bets,dependent: :destroy
	has_many :bet_items, through: :bets
	
	
	accepts_nested_attributes_for :bets, :allow_destroy => true, :reject_if => :all_blank



	# search for all events that have already been played
	def self.been_played(league)
		find(:all,:conditions => ['league_id = ? and date <= ?', league, Time.now])
	end

	# search for all events that have been played but results not entered
	def self.played_not_entered 
		find(:all,:conditions => ['date <= ? and (result =? or result is null)' ,Time.now,""])
	end




end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :signed_in_user, only: [:index, :resuts,:edit, :update, :destroy, :enter_result, :new, :enter_result, :enter_empty_results,:enter_results, :result, :search, :search_by_id, :save_result, :show]
  before_action :permited_user, only: [:new,:results, :enter_results,:update, :edit, :destroy, :enter_empty_results, :save_results, :create]
  def new
    @event = Event.new
     1.times do 
      bet = @event.bets.build
      1.times {bet.bet_items.build}
    end
    @leagues = League.all
   
      @league_id = params[:id]  # we need this incase the event is beig created from the league menu
    
  end

  def index
   
    @events = nil
    if params[:id].nil?
       @events = Event.all  # if the user didn't select a particluar league then list all events
     else
      @events = Event.been_played(params[:id])
    end
    respond_to do |format| 
        format.js
        format.html
      end
  end

  def enter_result  # used to enter the result on completed events
    @event = Event.find(params[:id])
    respond_to do |format|
      format.js
      format.html
    end
   

  end

  #find all events that have their result values empty so we can enter them
  def enter_empty_results

   @events = Event.played_not_entered

  end


  def result # present the results tab
    store_location
    @sports = League.all
    @status = "active"
  end

   def results # present the results tab
    store_location
    @sports = League.all
    @status = "active"
  end

  def search # method used to seach for a event
    searchstring = "%"+params[:q]+"%"
    @events = Event.where(Event.arel_table[:name].matches(searchstring))
      if (!@events) 
           flash[:warning] = "Event not found"
           redirect_to events_url

       
     
   
    end
  end
     def search_by_id # method used to seach for a event
    searchstring = params[:q].to_i
    @events = Event.where(:id => searchstring)
      if (!@events) 
           flash[:warning] = "Event not found"
           redirect_to events_url
      end
      render 'events/search'

  end



  # this method will collect the event ID from the user then present the form 
  # that allows the placing of bets----> currently not used
  def addbet

    @event = Event.find(params[:id])
   # @id = params[:id]

      
  end

  def save_result  # save the results of the event
    @event = Event.find(params[:id])
      if @event.update_attributes(result_params)
      flash[:success] = "Results Entered"
      redirect_to results_path
    else
      redirect_to 'enter_empty_results'
    end
    

  end

    def save_results  # when many results are being updated at once
      
       

      if Event.update(params[:event].keys, params[:event].values)
      flash[:success] = "Results Entered"
      redirect_to :back
    else
      redirect_to 'enter_results'
    end
    

  end


  #this method actually carries out the placing of bets
  def placebet
    @bet = Bet.create name: params[:betname], bet_type: params[:bettype],  event_id: params[:eventid] # create the bet object write to DB

    # create te betitems and link them to this bet
    @betitem1 = BetItem.create name: params[:betitem1name], odds: params[:betitem1odd], bet_id: @bet.id
    @betitem2 = BetItem.create name: params[:betitem2name], odds: params[:betitem2odd], bet_id: @bet.id
    @betitem3 = BetItem.create name: params[:betitem3name], odds: params[:betitem3odd], bet_id: @bet.id
     flash[:notice] = "Bet placed on" + Event.find(params[:eventid]).name
    redirect_to events_path
  end

  def removebet
    Bet.find(params[:id]).dexstroy
  end


  def showbets
    @event = params[:eventid]

    #check if this event has any bets
    @bets = Bet.find_by_event_id(event.id)
    # in the view we will only render the bets and thier respective bet items if !@bets.nil? is true
  end

  def show
    @event = Event.find(params[:id])
    @bets = @event.bets

    respond_to do |format|
      format.js
      format.html
    end
  end
 
  def create
    @event = Event.new(user_params) # save the event

       @event.date = params[:date]
    if !(params[:lid].nil?)
      @event.league_id = params[:lid]
    end
    
    if params[:event][:active]=="yes"
      @event.active = true;
    end
    if params[:event][:active]=="no"
      @event.active = false
    end 
    if @event.save
      flash[:notice] = "event successfully registered"
      redirect_to events_url
    else
      render 'new'
    end

  end

  def edit # edit league details
    @event = Event.find(params[:id])
   # @event.bets.build

  end

  def update
    @event = Event.find(params[:id])
    @event.date = params[:date]
   

    if params[:event][:active]=="yes"
      @event.active = true;
    end
    if params[:event][:active]=="no"
      @event.active = false
    end 
    if @event.update_attributes(user_params)
      flash[:success] = "Event updated"
      redirect_to events_path
    else
      render 'edit'
    end
  end

  def test_boot_strap

  end
  def destroy
    Event.find(params[:id]).destroy
    flash[:success] = "Event successfully deleted"
    redirect_to :back
  end

  def permited_user
    redirect_to (root_url) unless current_user.role_id <3
  end

  private
  def user_params # to prevent mass assginement security vulnerabily
    params.require(:event).permit(:name, :date, :league_id, :active, bets_attributes:[:id,:name, :bet_type_id, :_destroy, bet_items_attributes:[:id,:name,:odds,:_destroy]])
  end

  def result_params # prevent mass assignments and only update specific attributes of the event related to saving results
    params.require(:event).permit(:result, bets_attributes:[:id,bet_items_attributes:[:id,:name,:active]])
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_bet_results.html.erb
	
	
	
	<%= f.text_field :name, :disabled =>true %>

	 <aside class = "span3" align = "center">

	 <div class = "kaaywintable1" align="center">
		<table style = "width:200px" border=1 align="center">
	
	<tr><td>Pick</td></tr>

	<%= f.fields_for :bet_items do |f| %>
	
     <%= render 'events/bet_item_results' , :f =>f%>
    
     <%end%>
     

	</table>
	</aside>


   
	<br>
	
	
	<br>
	

app/views/events/_enter_empty_results.html.erb
<% provide(:title, "Result") %>
<div id = "replaceable">
<center><h1><%=event.name%></h1>

</center> 



<br>
<div class="row">
	<div class="span6 offset3">

<%= nested_form_for event, :url => url_for(:controller => "events", :action => "save_results") do |f|%>
	<%=render 'shared/error_messages_events_many', :event => event %>
	<%= f.label :result %>
	<%= f.text_field :result %>



	<%= f.fields_for :bets do |bet|%>
	<%= render 'events/bet_results', :f =>bet %>
	<%end%>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

	<%=f.submit "Submit Results", class: "btn btn-large btn-primary" %>

	<%end%>

</div>
</div>
</div>

app/views/events/_event.html.erb
<tr>
<td><%=event.id%></td>
<td><%=link_to event.name, display_event_path(event)%></td>
<td><%=event.date%></td>
<td><%=event.result%></td>

<td><%=event.active %></td>
<td><%=League.find(event.league_id).name %></td>


<% if current_user.role_id < 3%>
<td>

<%if !fromResultsMenu %>
<%= link_to "edit", edit_event_path(event)  %>
<%= link_to "delete", event, method: :delete, data: {confirm: "Are you sure?"} %>
<%end%>
<% if event.date < Time.now and fromResultsMenu%>
<%= link_to "enter results", result_path(:id => event.id) %>
<%end%>
</td></td>









<%end%>


</tr>

app/views/events/_show.html.erb
$('#replaceable').html("<%=j render partial: '/events/show'%>");

app/views/events/addbet.html.erb
<% provide(:title, "Add bet") %>

		
	<% @bets.each do |bet| %>
	<%=nested_form_for (bet) do |ff| %>
	<%=render 'shared/error_messages_bets' %>
	<table style = "width:320px" border=0>

	<tr><th><p align = "left"><%= ff.label :name %></p></th></tr>
	<tr><td><%= ff.text_field :name %></td></tr>

	<tr><th><p align = "left"><%= ff.label :bet_type %></p></th></tr>
	<tr><td><%= ff.text_field :bet_type %></td></tr>
	</table>
	

	
	
	
	<%=ff.fields_for :bet_item do |bet_item_form| %>
	<table style = "width:300px" border=0><tr><th>Name</th><th>Odds</th></tr></table>
		<table class = "bet_items" border = 1>
	


	<tr>

	<td><%= bet_item_form.text_field :name %></td>
	<td><%= bet_item_form.text_field :odds %></td>
	<tr>
	

	
	
	
	
	
	</table>
	<%= ff.link_to_add 'Add', :bet_items %>
	<br>
	<br>
	<% end %>
	
	
	

	<%=ff.submit "Create bet", class: "btn btn-large btn-primary" %>
	<%end%>
<%end%>

app/views/events/edit.html.erb
<% provide(:title, 'Edit Event') %>
<div class = "itemForm">
<h1>Please enter Event details: </h1>
<div class = "row">
	<div class = "span3 offset1">
		<%=nested_form_for(@event) do |f| %>
			<%=render 'shared/error_messages_events' %>
			<%= f.label :name %>
			<%= f.text_field :name %>

			
			
			<input type="text" class='tinytext' id="datetimepicker" name='date' value = "<%=@event.date%>" ></input>
			<script type="text/javascript">
  			$(function() {
   		 $('#datetimepicker').datetimepicker({
   		 	dateFormat : 'yy-mm-dd',
      		
   			 });
  			});
		</script>

			


			<%=f.label :active%>
			<%=f.check_box :active %>
			<br><br>

			<%= f.fields_for :bets %>
			 <p><%= f.link_to_add "Add bet", :bets %></p>
	

			<%=f.submit "Save changes", class: "btn btn-large btn-primary" %>
			<%end%>
		</div>
	</div>
	</div>

app/views/events/enter_result.html.erb
<% provide(:title, "Result for:"+@event.name) %>
<div id = "replaceable">
<center><h1><%=@event.name%></h1>

</center> 



<br>
<div class="row">
	<div class="span6 offset3">
<%= nested_form_for @event, :url => url_for(:controller => "events", :action => "save_result") do |f|%>
	<%=render 'shared/error_messages_events' %>
	<%= f.label :result %>
	<%= f.text_field :result %>



	<%= f.fields_for :bets do |bet|%>
	<%= render 'events/bet_results', :f =>bet %>
	<%end%>
	<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
	
<%=f.submit "Submit Results", class: "btn btn-large btn-primary" %>

	<%end%>

</div>
</div>
</div>

app/views/events/index.html.erb
<% provide(:title, "All Events") %>
<div class= "container">
<div class = "row">
<div class = "span10">
<center><h1>All Events</h1>
<%if current_user.role_id <3 %><%= button_to "Register a new event", new_event_path, method: :get%><%end%>
</center> 



<br>
<div class = "kaaywintable1">

<%fromResultsMenu = false%>

	
		
		<table>
	
		<td>id</td>
		<td>Name</td>
		<td>date</td>
		<td>result</td>
		<td>Active</td>
		<td>League</td>
		<td>Actions</td>


	<%= render @events, :fromResultsMenu => fromResultsMenu %>
	
	</table>
	
	<br>





</div>
</div>
</div>
</div>

app/views/events/new.html.erb
<% provide(:title, 'New Event') %>

<div class = "itemForm">
<h1>Please enter event details: </h1>

<br>
<br>
<br>
<div class = "row">
	<div class = "span3 offset1">
		<%= nested_form_for(@event) do |f| %>
			<%=render 'shared/error_messages_events' %>
			<p>
			<%= f.label :name %>
			<%= f.text_field :name %>

		
			<% if @league_id.nil? %>
			<label>League</label>
			
			<%=collection_select(:event, :league_id, League.all, :id, :name) %>
			<%else%>
			
			<%=hidden_field_tag "lid", League.find(@league_id).id %>

			

			
			<% end %>
			<%=f.label :date%>

			<input type="text" class='tinytext' id="datetimepicker" name='date'></input>
			<script type="text/javascript">
  			$(function() {
   		 $('#datetimepicker').datetimepicker({
   		 	dateFormat : 'yy-mm-dd',
      		
   			 });
  			});
		</script>


			


			

			<%=f.label :active%>
			<%=check_box("event", "active", {}, "yes", "no") %>
			<br><br>

			
			 <%= f.fields_for :bets %>
			 <p><%= f.link_to_add "Add bet", :bets %></p>
			 <br>
			 
			 
			<%=f.submit "Register this event", class: "btn btn-large btn-primary" %>
			
			<%end%>
		</div>
	</div>

	</div>

app/views/events/results.html.erb
<!-- Nav tabs -->
<%provide(:title, "results")%>
<div class= "container">
<div class = "row">
<div class = "span20">
 <div class = "tabbable">
<ul class="nav nav-tabs">
  
  <%statxus = "active"%>
 <li class = "active"><a href="#results" data-toggle="tab">All completed Events</a></li>
  <li class="inactive"><a href="#pending-entry" data-toggle="tab">All Pending result entries</a></li>
 
</ul>

<!-- Tab panes -->

<div class="tab-content">
<%fromResultsMenu = true %>
  <div class="tab-pane active" id="results">
        <div id = "replaceable">
        <h1> Sports </h1>
      <div class = "kaaywintable1">
      
	    <table>
	     <tr>
		      <td>Name</td>
		      <td>Date Created</td>
		      <td>Actions</td>
		  </tr>
    
      <%=render Sport.all, :fromResultsMenu => fromResultsMenu  %>

    </table>
    </div>
  </div>

</div>

 

<div class="tab-pane" id="pending-entry"> <%store_location%><%=render 'events/finished_events'%></div>


	


</div>
</div>
</div>
</div>
</div>

app/views/events/search.html.erb
<% provide(:title, "All Events") %>

<div id = "replaceable">
<div class= "container">
<div class = "row">
<div class = "span10">
<center><h1>All Events</h1>

<%if current_user.role_id <3 %><%= button_to "Register a new event", new_event_path, method: :get%><%end%>
</center> 


<% fromResultsMenu = false %>
<br>
<div class = "kaaywintable1">
  <table>



	<tr>
		<td>id</td>
		<td>Name</td>
		<td>date</td>
		<td>result</td>
		<td>Active</td>
		<td>League</td>
		<td>Actions</td>
		</tr>
	<%= render @events, :fromResultsMenu => fromResultsMenu %>
	
	</table>

	<br>





</table>

</div>
</div>
</div>
</div>
</div>

app/views/events/show.html.erb
<% provide(:title, @event.name) %>
<br>
<div id = "repleaceable">

		<center>
		<table border=1>
		<tr>
		<th>id</th>
		<th>Name</th>
		<th>date</th>
		<th>result</th>
		<th>Active</th>
		<th>League</th>
		
		<tr/>
		<tr>
		<td><%= @event.id %> </td>
		<td><%= @event.name %></td>
			<td><%= @event.date %></td>
			<td><%=@event.result%> </td>
			<td><%=@event.active %></td>
			<td><%=League.find(@event.league_id).name%></td>
		
			</tr>
			
			</table>

<br>
<% (@bets).each do |bet| %>
	Name: <%=bet.name%> <%=bet.bet_type.name%>
	<br>

	<table style = "width:500px" border=1>
	<tr><th>Name</th>
	<th>Odd</th>
	</tr>
	<% betItems = bet.bet_items%>
  
		
		
		<%betItems.each do |betItem| %>
		<tr>
			<td><%=betItem.name%></td>
			<td><%=betItem.odds%></td>
			</tr>

			
		<%end%>
		</table>
		
		
	<%end%>
	<%if current_user.role_id <3 %>
		<%= link_to "edit", edit_event_path(@event) %> 
		<%end%>	
</center>
		
		
</div>

app/views/events/test_boot_strap.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>Off Canvas Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="offcanvas.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </div><!-- /.navbar -->

    <div class="container">

      <div class="row row-offcanvas row-offcanvas-right">

        <div class="col-xs-12 col-sm-9">
          <p class="pull-right visible-xs">
            <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Toggle nav</button>
          </p>
          <div class="jumbotron">
            <h1>Hello, world!</h1>
            <p>This is an example to show the potential of an offcanvas layout pattern in Bootstrap. Try some responsive-range viewport sizes to see it in action.</p>
          </div>
          <div class="row">
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="col-6 col-sm-6 col-lg-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
            </div><!--/span-->
          </div><!--/row-->
        </div><!--/span-->

        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
          <div class="list-group">
            <a href="#" class="list-group-item active">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
            <a href="#" class="list-group-item">Link</a>
          </div>
        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div><!--/.container-->



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="offcanvas.js"></script>
  </body>
</html>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>